apiVersion: v1
kind: Service
metadata:
  name: wordcloud-microservice
spec:
  selector:
    app: wordcloud-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer